Repository MicrosoftDocs/azure-stack-docs, pull requests merged in 2023-03, with the labels that each got.

#2242 Remove ClientId and replace it with GUID as the name does not include ClientId
  azure-stack/operator/give-app-access-to-resources.md
Labels: Change sent to author, ready-to-merge, aq-pr-triaged, qualifies-for-auto-merge

#2247 Update aks-edge-concept-clusters-nodes.md
  AKS-Hybrid/aks-edge-concept-clusters-nodes.md
Labels: Change sent to author, do-not-merge, qualifies-for-auto-merge

#2252 fix a note format
  AKS-Hybrid/concepts-support.md
Labels: Change sent to author, ready-to-merge, qualifies-for-auto-merge

#2253 fix Gateway entry Register instead of Azure
  AKS-Hybrid/aks-hci-evaluation-guide-2a.md
Labels: Change sent to author, ready-to-merge, qualifies-for-auto-merge

#2257 fix PS variable WorkingDir
  AKS-Hybrid/aks-hybrid-preview-azure-vm.md
Labels: Change sent to author, ready-to-merge, aq-pr-triaged, qualifies-for-auto-merge

#2259 Update register-with-azure.md
  azure-stack/hci/deploy/register-with-azure.md
Labels: azure-stack/svc, Change sent to author, ready-to-merge, azure-stack-hci/subsvc, qualifies-for-auto-merge

#2267 Update azure-stack-identity-overview.md
  azure-stack/operator/azure-stack-identity-overview.md
Labels: Change sent to author, ready-to-merge, aq-pr-triaged, qualifies-for-auto-merge

#2262 remove SkipPublisherCheck switch
  AKS-Hybrid/includes/install-akshci-ps.md
Labels: azure-stack/svc, Change sent to author, ready-to-merge, aq-pr-triaged, qualifies-for-auto-merge

#2249 Update MetalLB configuration steps
  AKS-Hybrid/deploy-metallb.md
Labels: Change sent to author, ready-to-merge, aq-pr-triaged
